### ISSUE TITLE
Tags by events queries does not scale

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#175]
Already when reaching 10s of thousands of tagged events the paged tag-by-event query does not scale since the `LIMIT` is not dealt with from the index.

**Comment by chbatey** [comment]
This has been discussed in the couchbase forums here: https://forums.couchbase.com/t/problems-getting-unnest-query-to-use-nested-array-index/19556/6

Two options:
* Use the existing index but only query for document id so that the order by and limit will be pushed down
* Don't support atomic batches and insert a document per event however we'd still need an array for the tags and would need to verify that the index would push the ordering and limit down  

I'll spike the first one now
