### ISSUE TITLE
At least warn about missing indices

### ISSUE THREAD

**Issue by ygree** [akka/akka-persistence-couchbase#18]
It is silent about missing indices. It behaves like there are no events when the indices are missing.

**Comment by johanandren** [comment]
Since the create index operation has a "ignoreIfExists" I wonder if we can just always create the needed index if they are missing missing

**Comment by ygree** [comment]
It will fail if there is no necessary index exist. There is also index-autocreate setting:
https://github.com/akka/akka-persistence-couchbase/pull/81/

**Comment by johanandren** [comment]
Just to make a little note here: we tried this but had problems verifying in a deterministic way that the index is actually in place before the first plugin query happens. Just observing the API creation completing was not enough. We also tried polling the system bucket for indexes in progress, but that did also not quite help.

Additionally we saw warnings about unknown response 409 conflict from the client when we tried the only-create-if-doesn't-exist option.

Leaving this be for now since it will anyway not be safe for production systems, and we have seen users having issues with such functionality over and over again with the Cassandra persistence plugins.
