### ISSUE TITLE
Query backpressure

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#54]
We need to investigate if this somehow works out of the box (I don't think so, because rxJava), cover with some test coverage and if it doesn't work, see if we can solve it through pagination or something like that (https://blog.couchbase.com/optimizing-database-pagination-using-couchbase-n1ql/)

**Comment by ygree** [comment]
I’ve been trying to prove that Couchbase Java SDK doesn’t support back-pressure by trying to break it.
I thought there was no back pressure because I saw tcp packets kept going when it was still consuming the result set to the very end even when the stream was paused. It happens because it has enough internal buffers to accommodate lots of data and in my case there was relatively small amount of data requested (100k records). In fact when I run 12 concurrent queries returning 1M documents each they all finish successfully. It takes some time but it returns all the records correctly with no failures when the timeouts set large enough. I think since it uses tcp connection it effectively uses tcp back-pressure.

Couchbase Java SDK uses Netty under the hood. I was trying to minimize all internal buffers by setting all the Netty allocators settings to the minimum:

```System.setProperty("com.couchbase.client.deps.io.netty.allocator.pageSize", "4096") // minimum 4096
System.setProperty("com.couchbase.client.deps.io.netty.allocator.numHeapArenas", "0")
System.setProperty("com.couchbase.client.deps.io.netty.allocator.numDirectArenas", "0")
System.setProperty("com.couchbase.client.deps.io.netty.allocator.maxOrder", "0")
System.setProperty("com.couchbase.client.deps.io.netty.allocator.maxCachedBufferCapacity", "0")
System.setProperty("com.couchbase.client.deps.io.netty.allocator.cacheTrimInterval", "0")
System.setProperty("com.couchbase.client.deps.io.netty.allocator.useCacheForAllThreads", "false")
System.setProperty("com.couchbase.client.deps.io.netty.allocator.tinyCacheSize", "0")
System.setProperty("com.couchbase.client.deps.io.netty.allocator.smallCacheSize", "0")
System.setProperty("com.couchbase.client.deps.io.netty.allocator.normalCacheSize", "0")```


But despite all these it still works fine.

What’s more, when the stream fails it nicely cancels and it stops requesting data, e.g.:

```],
"status": "closed",
"metrics": {"elapsedTime": "1.2361925s","executionTime": "1.23615s","resultCount": 14646,"resultSize": 906416}
}```


All these leads me to the conclusion that there is in fact back-pressure in place.

**Comment by johanandren** [comment]
I think we need to mention this in the future Alpakka connector docs, and the Lagom Couchbase session docs, since it may surprise users.
