### ISSUE TITLE
Release through travis doesn't quite work

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#84]
First saw an error message about the release not existing, then when retriggered it said some files was already there, looking at bintray I see only artifacts for one Scala version (2.12) publishing 2.11 manually for now.

**Comment by johanandren** [comment]
Second failure: https://travis-ci.org/akka/akka-persistence-couchbase/jobs/456050492

**Comment by johanandren** [comment]
Again, this is after deleting the release, half of it goes well but then it starts saying there is no release 0.2:
[release-fail.log](https://github.com/akka/akka-persistence-couchbase/files/2659575/release-fail.log)

**Comment by 2m** [comment]
I have done some minor build/travis improvements in https://github.com/akka/akka-persistence-couchbase/pull/160 and https://github.com/akka/akka-persistence-couchbase/pull/161

There is one caveat when releasing with Travis where if a release tag is created immediately after the last PR has been merged, then the Travis job for the master branch after the merge becomes release job as well, because it also builds a commit that has a tag on it. Therefore we should wait until the master build completes after last PR merge or cancel that job and then create the release tag.

**Comment by johanandren** [comment]
Thanks for looking into and explaining!
